Repository Lightning-AI/LitServe, pull requests merged in 2024-05, with the labels that each got.

#79 decouple decode_request from get_batch_from_uid
  README.md
  src/litserve/server.py
  tests/test_batch.py
  tests/test_lit_server.py
Labels: enhancement

#87 improve logging
  README.md
  src/litserve/server.py
Labels: enhancement

#92 validate port
  src/litserve/server.py
  tests/test_lit_server.py
Labels: enhancement

#76 add openai spec v0
  README.md
  _requirements/test.txt
  src/litserve/api.py
  src/litserve/examples/openai_spec_example.py
  src/litserve/server.py
  src/litserve/specs/__init__.py
  src/litserve/specs/base.py
  src/litserve/specs/openai.py
  src/litserve/utils.py
  tests/conftest.py
  tests/e2e/default_spec.py
  tests/e2e/test_e2e.py
  tests/test_batch.py
  tests/test_lit_server.py
  tests/test_readme.py
  tests/test_specs.py
Labels: enhancement

#98 add client detail to streaming document
  README.md
  tests/e2e/default_batched_streaming.py
Labels: documentation

#105 add newline while streaming JSON objects
  src/litserve/api.py
Labels: enhancement

#108 fix pipe reuse
  src/litserve/server.py
  src/litserve/specs/openai.py
  tests/test_lit_server.py
Labels: bug

#101 add openai streaming
  README.md
  _requirements/test.txt
  src/litserve/examples/openai_spec_example.py
  src/litserve/server.py
  src/litserve/specs/openai.py
  src/litserve/utils.py
  tests/e2e/default_openaispec.py
  tests/e2e/test_e2e.py
  tests/test_readme.py
  tests/test_specs.py
Labels: enhancement, ci / tests

#119 feat: Update OpenAI spec to include support for tools
  README.md
  src/litserve/examples/openai_spec_example.py
  src/litserve/specs/openai.py
  tests/conftest.py
  tests/e2e/default_openaispec_tools.py
  tests/e2e/test_e2e.py
  tests/test_specs.py
Labels: enhancement
