Repository Lightning-AI/LitServe, pull requests merged in 2024-09, with the labels that each got.

#269 add perf test CI 1/3
  .azure/gpu-tests.yml
  _requirements/perf.txt
  tests/perf_test/bert/benchmark.py
  tests/perf_test/bert/data.py
  tests/perf_test/bert/run_test.sh
  tests/perf_test/bert/server.py
  tests/perf_test/bert/utils.py
Labels: ci / tests

#278 Callback system v0
  src/litserve/__init__.py
  src/litserve/callbacks/__init__.py
  src/litserve/callbacks/base.py
  src/litserve/callbacks/defaults/__init__.py
  src/litserve/callbacks/defaults/metric_callback.py
  src/litserve/loops.py
  src/litserve/server.py
  tests/test_batch.py
  tests/test_callbacks.py
  tests/test_loops.py
Labels: enhancement

#283 add streaming no-batch speed test
  .github/workflows/ci-parity.yml
  tests/perf_test/stream/run_test.sh
  tests/perf_test/stream/stream_speed/benchmark.py
  tests/perf_test/stream/stream_speed/server.py
Labels: ci / tests

#284 [Feat]: add Logger API
  src/litserve/__init__.py
  src/litserve/api.py
  src/litserve/loggers.py
  src/litserve/server.py
  tests/test_litapi.py
  tests/test_logger.py
Labels: enhancement

#297 update PR template with hiding instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#296 add links to forum and reduce opening issues for docs
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
Labels: enhancement

#300 Add warning for unexpected model output in batched prediction
  src/litserve/api.py
  tests/test_batch.py
Labels: good first issue

#302 fix custom HTTPException with argument names
  src/litserve/loops.py
  src/litserve/utils.py
  tests/test_lit_server.py
  tests/test_utils.py
Labels: bug

#303 fix vLLM capitalization
  README.md
Labels: documentation

#298 generate Dockerfile with CLI
  setup.py
  src/litserve/__main__.py
  src/litserve/docker_builder.py
  tests/test_docker_builder.py
Labels: enhancement

#306 add jsonargparse in requirements
  requirements.txt
Labels: bug
