Repository Lightning-AI/LitServe, pull requests merged in 2024-10, with the labels that each got.

#311 Enable gpu docker image generation
  src/litserve/docker_builder.py
  tests/test_docker_builder.py
Labels: enhancement

#312 update `dockerize` CLI success msg copy
  src/litserve/docker_builder.py
Labels: enhancement

#318 fix dockerize CLI test
  tests/test_docker_builder.py
Labels: bug, ci / tests

#319 fix(Logger): handle unpickleable Logger
  src/litserve/loggers.py
  tests/test_logger.py
Labels: bug

#322 test generate client file
  tests/test_lit_server.py
Labels: ci / tests

#324 avoid client generation if already exist
  src/litserve/python_client.py
  src/litserve/server.py
  tests/test_lit_server.py
Labels: bug

#327 enable isort
  pyproject.toml
  src/litserve/__init__.py
  src/litserve/__main__.py
  src/litserve/api.py
  src/litserve/callbacks/__init__.py
  src/litserve/callbacks/defaults/metric_callback.py
  src/litserve/docker_builder.py
  src/litserve/loggers.py
  src/litserve/specs/openai.py
  src/litserve/test_examples/__init__.py
  src/litserve/test_examples/openai_spec_example.py
  src/litserve/test_examples/simple_example.py
  src/litserve/utils.py
  tests/conftest.py
  tests/e2e/default_openai_with_batching.py
  tests/e2e/default_openaispec.py
  tests/e2e/default_openaispec_tools.py
  tests/e2e/default_single_streaming.py
  tests/e2e/default_spec.py
  tests/e2e/test_e2e.py
  tests/minimal_run.py
  tests/parity_fastapi/benchmark.py
  tests/parity_fastapi/ls-server.py
  tests/parity_fastapi/main.py
  tests/perf_test/bert/benchmark.py
  tests/perf_test/bert/server.py
  tests/simple_server.py
  tests/simple_server_diff_port.py
  tests/test_auth.py
  tests/test_batch.py
  tests/test_callbacks.py
  tests/test_cli.py
  tests/test_compression.py
  tests/test_connector.py
  tests/test_examples.py
  tests/test_form.py
  tests/test_litapi.py
  tests/test_logger.py
  tests/test_loops.py
  tests/test_pydantic.py
  tests/test_readme.py
  tests/test_simple.py
  tests/test_specs.py
  tests/test_torch.py
Labels: ci / tests

#346 Add dockerization to feature list
  README.md
Labels: documentation

#349 stream tool calling
  src/litserve/specs/openai.py
  tests/test_specs.py
Labels: bug
